### ISSUE TITLE
Making HTCrystallBall directly callable via the terminal without ./

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/HTCrystalBall#33] opened 2020-09-09 08:19 UTC
Hey,
I noticed, that for using your tool, I need to call it like ./htcrystalball.
In case that you want to call it directly via the terminal, independent to your dir, you can just add 
``` 
   scripts=[
        'htcrystalball'
    ],
```
to your setup.py file. This section makes the script directly available.

In case you want to compare, here you can see, that I also just have this small section in niiview as an example:
https://github.com/psyinfra/niiview/blob/master/setup.py

**Comment by mathisloevenich** [comment] 2020-09-09 08:24
This is related to #27, if already made a PR on that

**Comment by aqw** [comment] 2020-09-09 08:32
This is a duplicate of #27, and the PR #32 address it. Closing. :-)

**Closed by aqw** 2020-09-09 08:32 UTC
